name: NuGet Generation

on:
  push:
    branches:
      - main
      - release/*

  pull_request:
    branches:
      - main

jobs:
  calculate-version:
    name: Calculate Version
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.determineVersion.outputs.SemVer }}
      isProduction: ${{ steps.determineVersion.outputs.PreReleaseLabel == '' }}
      isReleaseCandidate: ${{ steps.determineVersion.outputs.PreReleaseLabel == 'rc' }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.10.2
        with:
          versionSpec: "5.x"

      - name: Determine Version
        id: determineVersion
        uses: gittools/actions/gitversion/execute@v0.10.2
        with:
          useConfigFile: true

  build:
    name: Update NuGet package
    needs: calculate-version
    runs-on: ubuntu-latest
    env:
      VERSION: ${{ needs.calculate-version.outputs.version }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .Net 7
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'        

      - name: Build solution and generate NuGet package
        run: |
          cd ./src/Keycloak.Net
          dotnet restore
          dotnet pack -c Release --include-symbols -o ../../artifacts /p:PackageVersion=${{ env.VERSION }}

      - name: Update NuGet Source to GitHub
        uses: actions/setup-dotnet@v3
        with:
          source-url: https://nuget.pkg.github.com/neothor/index.json
        env:
          NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - name: Push generated package to GitHub registry
        if: ${{ needs.calculate-version.outputs.isProduction == 'true' || needs.calculate-version.outputs.isReleaseCandidate == 'true' }}
        run: dotnet nuget push ./artifacts/*.nupkg --skip-duplicate -n

      - name: "Push tag"
        if: ${{ needs.calculate-version.outputs.isProduction == 'true' || needs.calculate-version.outputs.isReleaseCandidate == 'true' }}
        uses: thejeff77/action-push-tag@v1.0.0
        with:
          tag: ${{ needs.calculate-version.outputs.version }}

      - name: Create Release
        uses: ncipollo/release-action@v1
        if: ${{ needs.calculate-version.outputs.isProduction == 'true' || needs.calculate-version.outputs.isReleaseCandidate == 'true' }}
        with:
          allowUpdates: ${{ needs.calculate-version.outputs.isProduction != 'true' }}
          prerelease: ${{ needs.calculate-version.outputs.isProduction != 'true' }}
          tag: ${{ needs.calculate-version.outputs.version }}
