using System.Collections.Generic;
using System.Threading.Tasks;
using Keycloak.Net.Models.AttackDetection;
using Keycloak.Net.Models.AuthenticationManagement;
using Keycloak.Net.Models.ClientAttributeCertificate;
using Keycloak.Net.Models.ClientInitialAccess;
using Keycloak.Net.Models.Clients;
using Keycloak.Net.Models.ClientScopes;
using Keycloak.Net.Models.Common;
using Keycloak.Net.Models.Components;
using Keycloak.Net.Models.Groups;
using Keycloak.Net.Models.IdentityProviders;
using Keycloak.Net.Models.Key;
using Keycloak.Net.Models.ProtocolMappers;
using Keycloak.Net.Models.RealmsAdmin;
using Keycloak.Net.Models.Roles;
using Keycloak.Net.Models.Root;
using Keycloak.Net.Models.Users;
using Keycloak.Net.Models.UserStorageProvider;

namespace Keycloak.Net
{
  public interface IKeycloakClient
  {
    Task<bool> AddAuthenticationExecutionAsync(string realm, AuthenticationExecution authenticationExecution);
    Task<bool> AddAuthenticationFlowAndExecutionToAuthenticationFlowAsync(string realm, string flowAlias, IDictionary<string, object> dataWithAliasTypeProviderDescription);
    Task<bool> AddAuthenticationFlowExecutionAsync(string realm, string flowAlias, IDictionary<string, object> dataWithProvider);
    Task<bool> AddClientRoleMappingsToGroupAsync(string realm, string groupId, string clientId, IEnumerable<Role> roles);
    Task<bool> AddClientRoleMappingsToUserAsync(string realm, string userId, string clientId, IEnumerable<Role> roles);
    Task<bool> AddClientRolesScopeMappingToClientAsync(string realm, string clientId, IEnumerable<Role> roles);
    Task<bool> AddClientRolesToClientScopeAsync(string realm, string clientScopeId, string clientId, IEnumerable<Role> roles);
    Task<bool> AddCompositesToRoleAsync(string realm, string roleName, IEnumerable<Role> roles);
    Task<bool> AddCompositesToRoleAsync(string realm, string clientId, string roleName, IEnumerable<Role> roles);
    Task<bool> AddIdentityProviderMapperAsync(string realm, string identityProviderAlias, IdentityProviderMapper identityProviderMapper);
    Task<bool> AddRealmRoleMappingsToGroupAsync(string realm, string groupId, IEnumerable<Role> roles);
    Task<bool> AddRealmRoleMappingsToUserAsync(string realm, string userId, IEnumerable<Role> roles);
    Task<bool> AddRealmRolesScopeMappingToClientAsync(string realm, string clientId, IEnumerable<Role> roles);
    Task<bool> AddRealmRolesToClientScopeAsync(string realm, string clientScopeId, IEnumerable<Role> roles);
    Task<bool> AddUserSocialLoginProviderAsync(string realm, string userId, string provider, FederatedIdentity federatedIdentity);
    Task<Client> BasePathForImportingClientsAsync(string realm, string description);
    Task<bool> ClearKeysCacheAsync(string realm);
    Task<bool> ClearRealmCacheAsync(string realm);
    Task<bool> ClearUserCacheAsync(string realm);
    Task<bool> ClearUserLoginFailuresAsync(string realm);
    Task<bool> ClearUserLoginFailuresAsync(string realm, string userId);
    Task<bool> CorsPreflightAsync(string realm);
    Task<string> CreateAndRetrieveUserIdAsync(string realm, User user);
    Task<bool> CreateAuthenticationFlowAsync(string realm, AuthenticationFlow authenticationFlow);
    Task<bool> CreateClientAsync(string realm, Client client);
    Task<bool> CreateClientScopeAsync(string realm, ClientScope clientScope);
    Task<bool> CreateComponentAsync(string realm, Component componentRepresentation);
    Task<bool> CreateGroupAsync(string realm, Group group);
    Task<bool> CreateIdentityProviderAsync(string realm, Models.IdentityProviders.IdentityProvider identityProvider);
    Task<ClientInitialAccessPresentation> CreateInitialAccessTokenAsync(string realm, ClientInitialAccessCreatePresentation create);
    Task<bool> CreateMultipleProtocolMappersAsync(string realm, string clientScopeId, IEnumerable<ProtocolMapper> protocolMapperRepresentations);
    Task<bool> CreateProtocolMapperAsync(string realm, string clientScopeId, ProtocolMapper protocolMapperRepresentation);
    Task<bool> CreateRoleAsync(string realm, Role role);
    Task<bool> CreateRoleAsync(string realm, string clientId, Role role);
    Task<bool> CreateUserAsync(string realm, User user);
    Task<bool> DeleteAdminEventsAsync(string realm);
    Task<bool> DeleteAuthenticationExecutionAsync(string realm, string executionId);
    Task<bool> DeleteAuthenticationFlowAsync(string realm, string flowId);
    Task<bool> DeleteAuthenticatorConfigurationAsync(string realm, string configurationId);
    Task<bool> DeleteClientAsync(string realm, string clientId);
    Task<bool> DeleteClientRoleMappingsFromGroupAsync(string realm, string groupId, string clientId, IEnumerable<Role> roles);
    Task<bool> DeleteClientRoleMappingsFromUserAsync(string realm, string userId, string clientId, IEnumerable<Role> roles);
    Task<bool> DeleteClientScopeAsync(string realm, string clientScopeId);
    Task<bool> DeleteComponentAsync(string realm, string componentId);
    Task<bool> DeleteDefaultClientScopeAsync(string realm, string clientId, string clientScopeId);
    Task<bool> DeleteEventsAsync(string realm);
    Task<bool> DeleteGroupAsync(string realm, string groupId);
    Task<bool> DeleteIdentityProviderAsync(string realm, string identityProviderAlias);
    Task<bool> DeleteIdentityProviderMapperAsync(string realm, string identityProviderAlias, string mapperId);
    Task<bool> DeleteInitialAccessTokenAsync(string realm, string clientInitialAccessTokenId);
    Task<bool> DeleteOptionalClientScopeAsync(string realm, string clientId, string clientScopeId);
    Task<bool> DeleteProtocolMapperAsync(string realm, string clientScopeId, string protocolMapperId);
    Task<bool> DeleteRealmAsync(string realm);
    Task<bool> DeleteRealmDefaultClientScopeAsync(string realm, string clientScopeId);
    Task<bool> DeleteRealmGroupAsync(string realm, string groupId);
    Task<bool> DeleteRealmOptionalClientScopeAsync(string realm, string clientScopeId);
    Task<bool> DeleteRealmRoleMappingsFromGroupAsync(string realm, string groupId, IEnumerable<Role> roles);
    Task<bool> DeleteRealmRoleMappingsFromUserAsync(string realm, string userId, IEnumerable<Role> roles);
    Task<bool> DeleteRequiredActionAsync(string realm, string requiredActionAlias);
    Task<bool> DeleteRoleByIdAsync(string realm, string roleId);
    Task<bool> DeleteRoleByNameAsync(string realm, string roleName);
    Task<bool> DeleteRoleByNameAsync(string realm, string clientId, string roleName);
    Task<bool> DeleteUserAsync(string realm, string userId);
    Task<bool> DeleteUserGroupAsync(string realm, string userId, string groupId);
    Task<bool> DeleteUserSessionAsync(string realm, string session);
    Task<bool> DisableUserCredentialsAsync(string realm, string userId, IEnumerable<string> credentialTypes);
    Task<bool> DuplicateAuthenticationFlowAsync(string realm, string flowAlias, string newName);
    Task<bool> ExportIdentityProviderPublicBrokerConfigurationAsync(string realm, string identityProviderAlias);
    Task<byte[]> GenerateCertificateWithNewKeyPairAndGetKeyStoreAsync(string realm, string clientId, string attribute, KeyStoreConfig keyStoreConfig);
    Task<Certificate> GenerateCertificateWithNewKeyPairAsync(string realm, string clientId, string attribute);
    Task<AccessToken> GenerateClientExampleAccessTokenAsync(string realm, string clientId, string scope = null, string userId = null);
    Task<Client> GenerateClientRegistrationAccessTokenAsync(string realm, string clientId);
    Task<Credential> GenerateClientSecretAsync(string realm, string clientId);
    Task<IEnumerable<AdminEvent>> GetAdminEventsAsync(string realm, string authClient = null, string authIpAddress = null, string authRealm = null, string authUser = null, string dateFrom = null, string dateTo = null, int? first = null, int? max = null, IEnumerable<string> operationTypes = null, string resourcePath = null, IEnumerable<string> resourceTypes = null);
    Task<IEnumerable<Role>> GetApplicationRolesForCompositeAsync(string realm, string roleName, string forClientId);
    Task<IEnumerable<Role>> GetApplicationRolesForCompositeAsync(string realm, string clientId, string roleName, string forClientId);
    Task<AuthenticationExecutionById> GetAuthenticationExecutionAsync(string realm, string executionId);
    Task<AuthenticationFlow> GetAuthenticationFlowByIdAsync(string realm, string flowId);
    Task<IEnumerable<AuthenticationFlowExecution>> GetAuthenticationFlowExecutionsAsync(string realm, string flowAlias);
    Task<IEnumerable<AuthenticationFlow>> GetAuthenticationFlowsAsync(string realm);
    Task<AuthenticatorConfig> GetAuthenticatorConfigurationAsync(string realm, string configurationId);
    Task<AuthenticatorConfigInfo> GetAuthenticatorProviderConfigurationDescriptionAsync(string realm, string providerId);
    Task<IEnumerable<IDictionary<string, object>>> GetAuthenticatorProvidersAsync(string realm);
    Task<IEnumerable<Role>> GetAvailableClientRoleMappingsForGroupAsync(string realm, string groupId, string clientId);
    Task<IEnumerable<Role>> GetAvailableClientRoleMappingsForUserAsync(string realm, string userId, string clientId);
    Task<IEnumerable<Role>> GetAvailableClientRolesForClientScopeAsync(string realm, string clientScopeId, string clientId);
    Task<IEnumerable<Role>> GetAvailableClientRolesForClientScopeForClientAsync(string realm, string clientScopeId, string clientId);
    Task<IEnumerable<Role>> GetAvailableRealmRoleMappingsForGroupAsync(string realm, string groupId);
    Task<IEnumerable<Role>> GetAvailableRealmRoleMappingsForUserAsync(string realm, string userId);
    Task<IEnumerable<Role>> GetAvailableRealmRolesForClientScopeAsync(string realm, string clientScopeId);
    Task<IEnumerable<Role>> GetAvailableRealmRolesForClientScopeForClientAsync(string realm, string clientId);
    Task<Client> GetClientAsync(string realm, string clientId);
    Task<IEnumerable<IDictionary<string, object>>> GetClientAuthenticatorProvidersAsync(string realm);
    Task<ManagementPermission> GetClientAuthorizationPermissionsInitializedAsync(string realm, string clientId);
    Task<IEnumerable<Role>> GetClientGrantedScopeMappingsAsync(string realm, string clientId, string roleContainerId, string scope = null);
    Task<IEnumerable<ClientInitialAccessPresentation>> GetClientInitialAccessAsync(string realm);
    Task<IEnumerable<Role>> GetClientNotGrantedScopeMappingsAsync(string realm, string clientId, string roleContainerId, string scope = null);
    Task<int> GetClientOfflineSessionCountAsync(string realm, string clientId);
    Task<IEnumerable<UserSession>> GetClientOfflineSessionsAsync(string realm, string clientId, int? first = null, int? max = null);
    Task<string> GetClientProviderAsync(string realm, string clientId, string providerId);
    Task<IEnumerable<Role>> GetClientRoleMappingsForGroupAsync(string realm, string groupId, string clientId);
    Task<IEnumerable<Role>> GetClientRoleMappingsForUserAsync(string realm, string userId, string clientId);
    Task<IEnumerable<Role>> GetClientRolesForClientScopeAsync(string realm, string clientScopeId, string clientId);
    Task<IEnumerable<Role>> GetClientRolesForCompositeByIdAsync(string realm, string roleId, string clientId);
    Task<IEnumerable<Role>> GetClientRolesScopeMappingsForClientAsync(string realm, string clientId);
    Task<IEnumerable<Client>> GetClientsAsync(string realm, string clientId = null, bool? viewableOnly = null);
    Task<ClientScope> GetClientScopeAsync(string realm, string clientScopeId);
    Task<IEnumerable<ClientScope>> GetClientScopesAsync(string realm);
    Task<Credential> GetClientSecretAsync(string realm, string clientId);
    Task<int> GetClientSessionCountAsync(string realm, string clientId);
    Task<IEnumerable<IDictionary<string, object>>> GetClientSessionStatsAsync(string realm);
    Task<IEnumerable<UserSession>> GetClientUserSessionsAsync(string realm, string clientId, int? first = null, int? max = null);
    Task<Component> GetComponentAsync(string realm, string componentId);
    Task<IEnumerable<Component>> GetComponentsAsync(string realm, string name = null, string parent = null, string type = null);
    Task<IDictionary<string, object>> GetConfigurationDescriptionsForAllClientsAsync(string realm);
    Task<IEnumerable<ClientScope>> GetDefaultClientScopesAsync(string realm, string clientId);
    Task<IEnumerable<Role>> GetEffectiveClientRoleMappingsForGroupAsync(string realm, string groupId, string clientId);
    Task<IEnumerable<Role>> GetEffectiveClientRoleMappingsForUserAsync(string realm, string userId, string clientId);
    Task<IEnumerable<Role>> GetEffectiveClientRolesForClientScopeAsync(string realm, string clientScopeId, string clientId);
    Task<IEnumerable<Role>> GetEffectiveClientRolesForClientScopeForClientAsync(string realm, string clientScopeId, string clientId);
    Task<IEnumerable<Role>> GetEffectiveRealmRoleMappingsForGroupAsync(string realm, string groupId);
    Task<IEnumerable<Role>> GetEffectiveRealmRoleMappingsForUserAsync(string realm, string userId);
    Task<IEnumerable<Role>> GetEffectiveRealmRolesForClientScopeAsync(string realm, string clientScopeId);
    Task<IEnumerable<Role>> GetEffectiveRealmRolesForClientScopeForClientAsync(string realm, string clientId);
    Task<IEnumerable<Event>> GetEventsAsync(string realm, string client = null, string dateFrom = null, string dateTo = null, int? first = null, string ipAddress = null, int? max = null, string type = null, string user = null);
    Task<IEnumerable<IDictionary<string, object>>> GetFormActionProvidersAsync(string realm);
    Task<IEnumerable<IDictionary<string, object>>> GetFormProvidersAsync(string realm);
    Task<Group> GetGroupAsync(string realm, string groupId);
    Task<ManagementPermission> GetGroupClientAuthorizationPermissionsInitializedAsync(string realm, string groupId);
    Task<IEnumerable<Group>> GetGroupHierarchyAsync(string realm, int? first = null, int? max = null, string search = null);
    Task<int> GetGroupsCountAsync(string realm, string search = null, bool? top = null);
    Task<IEnumerable<Group>> GetGroupsWithRoleNameAsync(string realm, string roleName, int? first = null, bool? full = null, int? max = null);
    Task<IEnumerable<Group>> GetGroupsWithRoleNameAsync(string realm, string clientId, string roleName, int? first = null, bool? full = null, int? max = null);
    Task<IEnumerable<User>> GetGroupUsersAsync(string realm, string groupId);
    Task<Models.IdentityProviders.IdentityProvider> GetIdentityProviderAsync(string realm, string identityProviderAlias);
    Task<ManagementPermission> GetIdentityProviderAuthorizationPermissionsInitializedAsync(string realm, string identityProviderAlias);
    Task<IdentityProviderInfo> GetIdentityProviderByProviderIdAsync(string realm, string providerId);
    Task<IEnumerable<Models.IdentityProviders.IdentityProvider>> GetIdentityProviderInstancesAsync(string realm);
    Task<IdentityProviderMapper> GetIdentityProviderMapperByIdAsync(string realm, string identityProviderAlias, string mapperId);
    Task<IEnumerable<IdentityProviderMapper>> GetIdentityProviderMappersAsync(string realm, string identityProviderAlias);
    Task<IDictionary<string, object>> GetIdentityProviderMapperTypesAsync(string realm, string identityProviderAlias);
    Task<Certificate> GetKeyInfoAsync(string realm, string clientId, string attribute);
    Task<KeysMetadata> GetKeysAsync(string realm);
    Task<byte[]> GetKeyStoreForClientAsync(string realm, string clientId, string attribute, KeyStoreConfig keyStoreConfig);
    Task<IEnumerable<ClientScope>> GetOptionalClientScopesAsync(string realm, string clientId);
    Task<ProtocolMapper> GetProtocolMapperAsync(string realm, string clientScopeId, string protocolMapperId);
    Task<IEnumerable<ProtocolMapper>> GetProtocolMappersAsync(string realm, string clientScopeId);
    Task<IEnumerable<ProtocolMapper>> GetProtocolMappersByNameAsync(string realm, string clientScopeId, string protocol);
    Task<IEnumerable<ClientScopeEvaluateResourceProtocolMapperEvaluation>> GetProtocolMappersInTokenGenerationAsync(string realm, string clientId, string scope = null);
    Task<Realm> GetRealmAsync(string realm);
    Task<IEnumerable<ClientScope>> GetRealmDefaultClientScopesAsync(string realm);
    Task<RealmEventsConfig> GetRealmEventsProviderConfigurationAsync(string realm);
    Task<Group> GetRealmGroupByPathAsync(string realm, string path);
    Task<IEnumerable<Group>> GetRealmGroupHierarchyAsync(string realm);
    Task<IEnumerable<ClientScope>> GetRealmOptionalClientScopesAsync(string realm);
    Task<IEnumerable<Role>> GetRealmRoleMappingsForGroupAsync(string realm, string groupId);
    Task<IEnumerable<Role>> GetRealmRoleMappingsForUserAsync(string realm, string userId);
    Task<IEnumerable<Role>> GetRealmRolesForClientScopeAsync(string realm, string clientScopeId);
    Task<IEnumerable<Role>> GetRealmRolesForCompositeAsync(string realm, string roleName);
    Task<IEnumerable<Role>> GetRealmRolesForCompositeAsync(string realm, string clientId, string roleName);
    Task<IEnumerable<Role>> GetRealmRolesForCompositeByIdAsync(string realm, string roleId);
    Task<IEnumerable<Role>> GetRealmRolesScopeMappingsForClientAsync(string realm, string clientId);
    Task<ManagementPermission> GetRealmUsersManagementPermissionsAsync(string realm);
    Task<RequiredActionProvider> GetRequiredActionByAliasAsync(string realm, string requiredActionAlias);
    Task<IEnumerable<RequiredActionProvider>> GetRequiredActionsAsync(string realm);
    Task<IEnumerable<ComponentType>> GetRetrieveProvidersBasePathAsync(string realm);
    Task<ManagementPermission> GetRoleAuthorizationPermissionsInitializedAsync(string realm, string roleName);
    Task<ManagementPermission> GetRoleAuthorizationPermissionsInitializedAsync(string realm, string clientId, string roleName);
    Task<Role> GetRoleByIdAsync(string realm, string roleId);
    Task<ManagementPermission> GetRoleByIdAuthorizationPermissionsInitializedAsync(string realm, string roleId);
    Task<Role> GetRoleByNameAsync(string realm, string roleName);
    Task<Role> GetRoleByNameAsync(string realm, string clientId, string roleName);
    Task<IEnumerable<Role>> GetRoleChildrenAsync(string realm, string roleId);
    Task<IEnumerable<Role>> GetRoleCompositesAsync(string realm, string roleName);
    Task<IEnumerable<Role>> GetRoleCompositesAsync(string realm, string clientId, string roleName);
    Task<Mapping> GetRoleMappingsForGroupAsync(string realm, string groupId);
    Task<Mapping> GetRoleMappingsForUserAsync(string realm, string userId);
    Task<IEnumerable<Role>> GetRolesAsync(string realm);
    Task<IEnumerable<Role>> GetRolesAsync(string realm, string clientId);
    Task<Mapping> GetScopeMappingsAsync(string realm, string clientScopeId);
    Task<Mapping> GetScopeMappingsForClientAsync(string realm, string clientId);
    Task<ServerInfo> GetServerInfoAsync(string realm);
    Task<IEnumerable<ComponentType>> GetSubcomponentTypesAsync(string realm, string componentId, string type = null);
    Task<IEnumerable<IDictionary<string, object>>> GetUnregisteredRequiredActionsAsync(string realm);
    Task<User> GetUserAsync(string realm, string userId);
    Task<string> GetUserConsentsAsync(string realm, string userId);
    Task<User> GetUserForServiceAccountAsync(string realm, string clientId);
    Task<IEnumerable<Group>> GetUserGroupsAsync(string realm, string userId);
    Task<int> GetUserGroupsCountAsync(string realm, string userId);
    Task<UserNameStatus> GetUserNameStatusInBruteForceDetectionAsync(string realm, string userId);
    Task<IEnumerable<UserSession>> GetUserOfflineSessionsAsync(string realm, string userId, string clientId);
    Task<IEnumerable<User>> GetUsersAsync(string realm, bool? briefRepresentation = null, string email = null, int? first = null, string firstName = null, string lastName = null, int? max = null, string search = null, string username = null);
    Task<int> GetUsersCountAsync(string realm);
    Task<IEnumerable<UserSession>> GetUserSessionsAsync(string realm, string userId);
    Task<IEnumerable<FederatedIdentity>> GetUserSocialLoginsAsync(string realm, string userId);
    Task<IEnumerable<User>> GetUsersWithRoleNameAsync(string realm, string roleName, int? first = null, int? max = null);
    Task<IEnumerable<User>> GetUsersWithRoleNameAsync(string realm, string clientId, string roleName, int? first = null, int? max = null);
    Task<IDictionary<string, object>> ImpersonateUserAsync(string realm, string userId);
    Task<IDictionary<string, object>> ImportIdentityProviderAsync(string realm, string input);
    Task<bool> ImportRealmAsync(string realm, Realm rep);
    Task<bool> LowerAuthenticationExecutionPriorityAsync(string realm, string executionId);
    Task<bool> LowerRequiredActionPriorityAsync(string realm, string requiredActionAlias);
    Task<bool> MakeRoleCompositeAsync(string realm, string roleId, IEnumerable<Role> roles);
    Task<GlobalRequestResult> PushClientRevocationPolicyAsync(string realm, string clientId);
    Task<GlobalRequestResult> PushRealmRevocationPolicyAsync(string realm);
    Task<bool> RaiseAuthenticationExecutionPriorityAsync(string realm, string executionId);
    Task<bool> RaiseRequiredActionPriorityAsync(string realm, string requiredActionAlias);
    Task<Realm> RealmPartialExportAsync(string realm, bool? exportClients = null, bool? exportGroupsAndRoles = null);
    Task<bool> RealmPartialImportAsync(string realm, PartialImport rep);
    Task<bool> RegisterClientClusterNodeAsync(string realm, string clientId, IDictionary<string, object> formParams);
    Task<bool> RegisterRequiredActionAsync(string realm, IDictionary<string, object> dataWithProviderIdName);
    Task<bool> RemoveClientRolesFromClientScopeAsync(string realm, string clientScopeId, string clientId, IEnumerable<Role> roles);
    Task<bool> RemoveClientRolesFromClientScopeForClientAsync(string realm, string clientId, IEnumerable<Role> roles);
    Task<bool> RemoveCompositesFromRoleAsync(string realm, string roleName, IEnumerable<Role> roles);
    Task<bool> RemoveCompositesFromRoleAsync(string realm, string clientId, string roleName, IEnumerable<Role> roles);
    Task<bool> RemoveImportedUsersAsync(string realm, string storageProviderId);
    Task<bool> RemoveRealmRolesFromClientScopeAsync(string realm, string clientScopeId, IEnumerable<Role> roles);
    Task<bool> RemoveRealmRolesFromClientScopeForClientAsync(string realm, string clientId, IEnumerable<Role> roles);
    Task<bool> RemoveRolesFromCompositeAsync(string realm, string roleId, IEnumerable<Role> roles);
    Task<GlobalRequestResult> RemoveUserSessionsAsync(string realm);
    Task<bool> RemoveUserSessionsAsync(string realm, string userId);
    Task<bool> RemoveUserSocialLoginProviderAsync(string realm, string userId, string provider);
    Task<bool> RemoveUserTotpAsync(string realm, string userId);
    Task<bool> ResetUserPasswordAsync(string realm, string userId, string password);
    Task<bool> RevokeUserConsentAndOfflineTokensAsync(string realm, string userId, string clientId);
    Task<bool> SendUserUpdateAccountEmailAsync(string realm, string userId, IEnumerable<string> requiredActions, string clientId = null, int? lifespan = null, string redirectUri = null);
    Task<ManagementPermission> SetClientAuthorizationPermissionsInitializedAsync(string realm, string clientId, ManagementPermission managementPermission);
    Task<ManagementPermission> SetGroupClientAuthorizationPermissionsInitializedAsync(string realm, string groupId, ManagementPermission managementPermission);
    Task<ManagementPermission> SetIdentityProviderAuthorizationPermissionsInitializedAsync(string realm, string identityProviderAlias, ManagementPermission managementPermission);
    Task<bool> SetOrCreateGroupChildAsync(string realm, string groupId, Group group);
    Task<ManagementPermission> SetRoleAuthorizationPermissionsInitializedAsync(string realm, string roleName, ManagementPermission managementPermission);
    Task<ManagementPermission> SetRoleAuthorizationPermissionsInitializedAsync(string realm, string clientId, string roleName, ManagementPermission managementPermission);
    Task<ManagementPermission> SetRoleByIdAuthorizationPermissionsInitializedAsync(string realm, string roleId, ManagementPermission managementPermission);
    Task<GlobalRequestResult> TestClientClusterNodesAvailableAsync(string realm, string clientId);
    Task<bool> TestLdapConnectionAsync(string realm, string action = null, string bindCredential = null, string bindDn = null, string componentId = null, string connectionTimeout = null, string connectionUrl = null, string useTruststoreSpi = null);
    Task<bool> TestSmtpConnectionAsync(string realm, string config);
    Task<SynchronizationResult> TriggerLdapMapperSynchronizationAsync(string realm, string storageProviderId, string mapperId, LdapMapperSyncActions direction);
    Task<SynchronizationResult> TriggerUserSynchronizationAsync(string realm, string storageProviderId, UserSyncActions action);
    Task<bool> UnlinkImportedUsersAsync(string realm, string storageProviderId);
    Task<bool> UnregisterClientClusterNodeAsync(string realm, string clientId);
    Task<bool> UpdateAuthenticationExecutionConfigurationAsync(string realm, string executionId, AuthenticatorConfig authenticatorConfig);
    Task<bool> UpdateAuthenticationFlowAsync(string realm, string flowId, AuthenticationFlow authenticationFlow);
    Task<bool> UpdateAuthenticationFlowExecutionsAsync(string realm, string flowAlias, AuthenticationExecutionInfo authenticationExecutionInfo);
    Task<bool> UpdateAuthenticatorConfigurationAsync(string realm, string configurationId, AuthenticatorConfig authenticatorConfig);
    Task<bool> UpdateClientAsync(string realm, string clientId, Client client);
    Task<bool> UpdateClientScopeAsync(string realm, string clientScopeId, ClientScope clientScope);
    Task<bool> UpdateComponentAsync(string realm, string componentId, Component componentRepresentation);
    Task<bool> UpdateDefaultClientScopeAsync(string realm, string clientId, string clientScopeId);
    Task<bool> UpdateGroupAsync(string realm, string groupId, Group group);
    Task<bool> UpdateIdentityProviderAsync(string realm, string identityProviderAlias, Models.IdentityProviders.IdentityProvider identityProvider);
    Task<bool> UpdateIdentityProviderMapperAsync(string realm, string identityProviderAlias, string mapperId, IdentityProviderMapper identityProviderMapper);
    Task<bool> UpdateOptionalClientScopeAsync(string realm, string clientId, string clientScopeId);
    Task<bool> UpdateProtocolMapperAsync(string realm, string clientScopeId, string protocolMapperId, ProtocolMapper protocolMapperRepresentation);
    Task<bool> UpdateRealmAsync(string realm, Realm rep);
    Task<bool> UpdateRealmDefaultClientScopeAsync(string realm, string clientScopeId);
    Task<bool> UpdateRealmEventsProviderConfigurationAsync(string realm, RealmEventsConfig rep);
    Task<bool> UpdateRealmGroupAsync(string realm, string groupId);
    Task<bool> UpdateRealmOptionalClientScopeAsync(string realm, string clientScopeId);
    Task<ManagementPermission> UpdateRealmUsersManagementPermissionsAsync(string realm, ManagementPermission managementPermission);
    Task<bool> UpdateRequiredActionAsync(string realm, string requiredActionAlias, RequiredActionProvider requiredActionProvider);
    Task<bool> UpdateRoleByIdAsync(string realm, string roleId, Role role);
    Task<bool> UpdateRoleByNameAsync(string realm, string roleName, Role role);
    Task<bool> UpdateRoleByNameAsync(string realm, string clientId, string roleName, Role role);
    Task<bool> UpdateUserAsync(string realm, string userId, User user);
    Task<bool> UpdateUserGroupAsync(string realm, string userId, string groupId, Group group);
    Task<Certificate> UploadCertificateWithoutPrivateKeyAsync(string realm, string clientId, string attribute, string fileName);
    Task<Certificate> UploadCertificateWithPrivateKeyAsync(string realm, string clientId, string attribute, string fileName);
    Task<bool> VerifyUserEmailAddressAsync(string realm, string userId, string clientId = null, string redirectUri = null);
  }
}